[package]
name = "wezlix"
version = "0.1.1"
edition = "2021"
default-run = "wezlix-builder"

[[bin]]
name = "wezlix-builder"
path = "src/wezlix-builder.rs"

[[bin]]
name = "wezlix"
path = "src/wezlix.rs"

[dependencies]
# Command line argument parsing
clap = { version = "4.4.16", features = ["derive", "env"] }

# Recursively copy files
fs_extra = "1.3.0"

# Generate icons from SVG
resvg = "0.37.0"
tiny-skia = "0.11.3"
usvg = "0.37.0"

# Generate info.plist
apple-bundle = "0.1.4"

# Configuration directory
xdg = "2.5.2"
home = "0.5.9"
